# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20160220_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=b'newUser', unique=True, verbose_name=b'Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=b'nombre de usuario'),
        ),
    ]
