# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 14:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20160220_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message=b'Escriba su n\xc3\xbamero celular en 10 d\xc3\xadgitos', regex=b'^[0-9]*$')], verbose_name=b'N\xc3\xbamero m\xc3\xb3vil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, unique=True, verbose_name=b'Email'),
        ),
    ]
