# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20160220_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
    ]
