# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Fecha de actualizaci\xc3\xb3n'),
        ),
    ]
