# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True, verbose_name=b'Slug'),
        ),
    ]
